name: Release CodeRevealer

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create directory structure
        run: |
          mkdir -p CodeRevealer/Scripts
          touch CodeRevealer/enabled.txt
          cp ue4ss_mod/main.lua CodeRevealer/Scripts/main.lua

      - name: Zip files
        run: |
          zip -r CodeRevealer.zip CodeRevealer

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          prerelease: false
          files: |
            CodeRevealer.zip

permissions:
  contents: write
